bootstrap.servers=localhost:9092
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.ScramLoginModule required \
    username="alice" \
    password="alice-secret";

# --- The Isolation Level ---
isolation.level=read_committed
