# Connect to the external listener
bootstrap.servers=localhost:9092,localhost:9094,localhost:9096

# Protocol Configuration
security.protocol=SASL_PLAINTEXT
sasl.mechanism=PLAIN

# JAAS Configuration (User: admin, Password: admin-secret)
# Note: The semicolons at the end of the line are required syntax.
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required \
    username="admin" \
    password="admin-secret";
